### ISSUE TITLE
SHREC 2017 Dataset

### ISSUE THREAD

**Issue by QienJane** [humansensinglab/dfcil-hgr#2]
Hello, the official website "http://www-rech.telecom-lille.fr/shrec2017-hand/" for downloading the SHREC17 dataset is no longer accessible.

Can you provide me with the following files from the SHREC17 dataset? If you can provide them, it would be a great help to my research.

Specifically, include: The overall folder that contains the folders "gesture_1" to "gesture_14".

This overall folder contains the following files:
+---gesture_1
| +---finger_1
| | +---subject_1
| | | +---essai_1
| | | | | |   
| | | | depth_0.png
| | | | depth_1.png
| | | | | | | | ...
| | | | depth_N-1.png
| | | | general_informations.txt
| | | skeletons_image.txt
| | | skeletons_world.txt
| | | | | |
| | | ---essai_2
| | | ...
| | ---essai_5
| ---subject_2
| ...
| ---subject_20
| ---finger_2
...
---gesture_14

**Comment by sunao-101** [comment]
Good brother, have you found this dataset? I am also missing this dataset

**Comment by QienJane** [comment]
No, I've tried a lot of endeavors, but they all contain the raw files in .obj format.

I haven't seen anyone share the overall folder that contains the folders "gesture_1" to "gesture_14".

We can communicate more about this dataset. This dataset is important for my further research on gesture recognition.

**Comment by QienJane** [comment]
Hello, The DHG-14/28 dataset you provided is very similar to the contents of the SHREC 2017 dataset.

But the official website "http://www-rech.telecom-lille.fr/shrec2017-hand/" for downloading the SHREC17 dataset is no longer accessible.

Can you provide me with the following files from the SHREC17 dataset? If you can provide them, it would be a great help to my research.

The SHREC17 dataset include the overall folder that contains the folders "gesture_1" to "gesture_14".
This overall folder contains the following files:
+---gesture_1
| +---finger_1
| | +---subject_1
| | | +---essai_1
| | | | | |   
| | | | depth_0.png
| | | | depth_1.png
| | | | | | | | ...
| | | | depth_N-1.png
| | | | general_informations.txt
| | | skeletons_image.txt
| | | skeletons_world.txt
| | | | | |
| | | ---essai_2
| | | ...
| | ---essai_5
| ---subject_2
| ...
| ---subject_20
| ---finger_2
...
---gesture_14

**Comment by sunao-101** [comment]
Are you Chinese? We can add a WeChat account. I contacted the original author who proposed this dataset paper, and he replied to me, asking what part I need. Maybe he can reply to me tomorrow. If it is the same as the dataset provided on the official website, I can give you a copy. I have only downloaded the pkl file now

**Comment by QienJane** [comment]
Yes！ Thank you!
